# Compose file to set up invoice management database database. THe database has tables that records customer order details.

version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"